# Generated by Django 6.0.6 on 2026-07-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_created_at_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pomodoro_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
