# Generated by Django 6.0.6 on 2026-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_pomodoro_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timer_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
